<?php require_once __DIR__ . '/includes/admin-header.php'; exigir_perfil(['administrador','gerencial']);
if($_SERVER['REQUEST_METHOD']==='POST'){ validar_csrf();
 if(isset($_POST['salvar_ajustes'])){ $logoPath=$_POST['logo_atual']??''; if(!empty($_FILES['logo']['name'])){ $ext=strtolower(pathinfo($_FILES['logo']['name'],PATHINFO_EXTENSION)); if(in_array($ext,['png','jpg','jpeg','webp','svg'],true)){ $nome='logo-'.time().'.'.$ext; $destino=__DIR__.'/../assets/img/'.$nome; if(move_uploaded_file($_FILES['logo']['tmp_name'],$destino)){ chmod($destino, 0644); $logoPath='assets/img/'.$nome; } } } $dados=['nome_loja'=>$_POST['nome_loja'],'titulo_pagina'=>$_POST['titulo_pagina'],'contato_topo'=>$_POST['contato_topo'],'contato_footer'=>$_POST['contato_footer'],'texto_footer'=>$_POST['texto_footer'],'logo'=>$logoPath]; foreach($dados as $chave=>$valor){$pdo->prepare('INSERT INTO ajustes_pagina (chave,valor) VALUES (?,?) ON DUPLICATE KEY UPDATE valor=VALUES(valor)')->execute([$chave,$valor]);} registrar_log($pdo,'Ajuste de página','Atualizou identidade e contatos'); }
 if(isset($_POST['novo_menu'])){ $pdo->prepare('INSERT INTO menus (titulo,url,ordem,ativo) VALUES (?,?,?,1)')->execute([$_POST['titulo'],$_POST['url'],$_POST['ordem']]); registrar_log($pdo,'Menus','Criou menu '.$_POST['titulo']); }
 if(isset($_POST['excluir_menu'])){ $pdo->prepare('DELETE FROM menus WHERE id=?')->execute([$_POST['id']]); registrar_log($pdo,'Menus','Excluiu menu ID '.$_POST['id']); }
}
$aj=buscar_ajustes($pdo); $menus=$pdo->query('SELECT * FROM menus ORDER BY ordem,id')->fetchAll();
?>
<h1>Ajuste de página</h1><div class="grid-2"><section class="panel"><h2>Identidade, contatos e footer</h2><form method="post" enctype="multipart/form-data" class="form-grid"><input type="hidden" name="csrf_token" value="<?= csrf_token() ?>"><input type="hidden" name="logo_atual" value="<?= e($aj['logo']??'') ?>"><label>Nome da loja<input name="nome_loja" value="<?= e($aj['nome_loja']??'PROHOSP') ?>"></label><label>Título da página<input name="titulo_pagina" value="<?= e($aj['titulo_pagina']??'PROHOSP') ?>"></label><label>Logo<input type="file" name="logo"></label><label>Contato topo<input name="contato_topo" value="<?= e($aj['contato_topo']??'') ?>"></label><label>Contato footer<input name="contato_footer" value="<?= e($aj['contato_footer']??'') ?>"></label><label class="wide">Texto footer<textarea name="texto_footer"><?= e($aj['texto_footer']??'') ?></textarea></label><button class="btn primary" name="salvar_ajustes">Salvar ajustes</button></form></section><section class="panel"><h2>Menus</h2><form method="post" class="form-grid compact"><input type="hidden" name="csrf_token" value="<?= csrf_token() ?>"><label>Título<input name="titulo" required></label><label>Aponta para página/item<input name="url" placeholder="index.php#produtos" required></label><label>Ordem<input name="ordem" type="number" value="1"></label><button class="btn primary" name="novo_menu">Criar menu</button></form><div class="table-wrap"><table><thead><tr><th>Título</th><th>URL</th><th>Ordem</th><th></th></tr></thead><tbody><?php foreach($menus as $m): ?><tr><td><?= e($m['titulo']) ?></td><td><?= e($m['url']) ?></td><td><?= (int)$m['ordem'] ?></td><td><form method="post"><input type="hidden" name="csrf_token" value="<?= csrf_token() ?>"><input type="hidden" name="id" value="<?= (int)$m['id'] ?>"><button name="excluir_menu">Excluir</button></form></td></tr><?php endforeach; ?></tbody></table></div></section></div><?php require_once __DIR__ . '/includes/admin-footer.php'; ?>
