<?php require_once __DIR__ . '/includes/admin-header.php';
function salvar_imagem_produto(): string { if (empty($_FILES['imagem']['name'])) return ''; $ext=strtolower(pathinfo($_FILES['imagem']['name'], PATHINFO_EXTENSION)); $permitidas=['jpg','jpeg','png','webp','svg']; if(!in_array($ext,$permitidas,true)) return ''; if(!is_dir(UPLOAD_PROD_DIR)) mkdir(UPLOAD_PROD_DIR,0755,true); $nome='prod-'.date('YmdHis').'-'.bin2hex(random_bytes(4)).'.'.$ext; move_uploaded_file($_FILES['imagem']['tmp_name'], UPLOAD_PROD_DIR.$nome); return UPLOAD_PROD_URL.$nome; }
if ($_SERVER['REQUEST_METHOD'] === 'POST') { validar_csrf();
 if(isset($_POST['excluir'])) { $pdo->prepare('UPDATE produtos SET ativo=0 WHERE id=?')->execute([$_POST['id']]); registrar_log($pdo,'Produtos','Desativou produto ID '.$_POST['id']); }
 else { $imagem=salvar_imagem_produto(); $id=$_POST['id']??''; if($id){ $sql='UPDATE produtos SET codigo=?, codigo_interno=?, descricao=?, tipo=?, categoria=?, preco=?, ativo=?'.($imagem?', imagem=?':'').' WHERE id=?'; $params=[$_POST['codigo'],$_POST['codigo_interno'],$_POST['descricao'],$_POST['tipo'],$_POST['categoria'],$_POST['preco'],isset($_POST['ativo'])?1:0]; if($imagem)$params[]=$imagem; $params[]=$id; $pdo->prepare($sql)->execute($params); registrar_log($pdo,'Produtos','Atualizou produto ID '.$id); } else { $pdo->prepare('INSERT INTO produtos (codigo,codigo_interno,descricao,tipo,categoria,preco,imagem,ativo,criado_em) VALUES (?,?,?,?,?,?,?,?,NOW())')->execute([$_POST['codigo'],$_POST['codigo_interno'],$_POST['descricao'],$_POST['tipo'],$_POST['categoria'],$_POST['preco'],$imagem,isset($_POST['ativo'])?1:0]); registrar_log($pdo,'Produtos','Criou produto '.$_POST['descricao']); } }
}
$editar=null; if(isset($_GET['editar'])) { $st=$pdo->prepare('SELECT * FROM produtos WHERE id=?'); $st->execute([$_GET['editar']]); $editar=$st->fetch(); }
$produtos=$pdo->query('SELECT * FROM produtos ORDER BY id DESC')->fetchAll();
$tipos=['UN','CX','PC','BS']; $cats=['Medicamento','Material hospitalar'];
?>
<h1>Cadastro de produtos</h1><p class="muted">Imagens salvas em <b>/data/img-prod</b> e caminho registrado no banco.</p>
<div class="grid-2"><section class="panel"><h2><?= $editar?'Editar':'Novo' ?> produto</h2><form method="post" enctype="multipart/form-data" class="form-grid"><input type="hidden" name="csrf_token" value="<?= csrf_token() ?>"><input type="hidden" name="id" value="<?= e($editar['id']??'') ?>"><label>Código<input name="codigo" required value="<?= e($editar['codigo']??'') ?>"></label><label>Cód. interno<input name="codigo_interno" required value="<?= e($editar['codigo_interno']??'') ?>"></label><label class="wide">Descrição<input name="descricao" required value="<?= e($editar['descricao']??'') ?>"></label><label>Tipo<select name="tipo"><?php foreach($tipos as $t): ?><option <?= ($editar['tipo']??'')===$t?'selected':'' ?>><?= $t ?></option><?php endforeach; ?></select></label><label>Categoria<select name="categoria"><?php foreach($cats as $c): ?><option <?= ($editar['categoria']??'')===$c?'selected':'' ?>><?= $c ?></option><?php endforeach; ?></select></label><label>Preço<input type="number" step="0.01" name="preco" value="<?= e($editar['preco']??'0.00') ?>"></label><label>Imagem<input type="file" name="imagem" accept=".jpg,.jpeg,.png,.webp,.svg"></label><label class="check"><input type="checkbox" name="ativo" <?= ($editar['ativo']??1)?'checked':'' ?>> Ativo</label><button class="btn primary">Salvar produto</button></form></section><section class="panel"><h2>Produtos</h2><div class="table-wrap"><table><thead><tr><th>Cód.</th><th>Descrição</th><th>Tipo</th><th>Categoria</th><th>Preço</th><th></th></tr></thead><tbody><?php foreach($produtos as $p): ?><tr><td><?= e($p['codigo']) ?></td><td><?= e($p['descricao']) ?></td><td><?= e($p['tipo']) ?></td><td><?= e($p['categoria']) ?></td><td><?= moeda($p['preco']) ?></td><td><a href="?editar=<?= (int)$p['id'] ?>">Editar</a><form method="post" class="inline"><input type="hidden" name="csrf_token" value="<?= csrf_token() ?>"><input type="hidden" name="id" value="<?= (int)$p['id'] ?>"><button name="excluir">Excluir</button></form></td></tr><?php endforeach; ?></tbody></table></div></section></div>
<?php require_once __DIR__ . '/includes/admin-footer.php'; ?>
